# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/aushinpullattu/9d686c3c08c6ae1f97e74bedb8b9348b/untitled3.ipynb
"""

!pip install streamlit
!apt install -y wget

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# from PIL import Image
# import smtplib
# from email.mime.text import MIMEText
# from email.mime.multipart import MIMEMultipart
# 
# st.set_page_config(page_title="Send a Postcard 💌", layout="centered")
# st.title("📮 Send a Postcard")
# 
# postcard = Image.open("postcard_template.png")
# st.image(postcard, use_container_width=True)
# 
# to_name = st.text_input("To")
# from_name = st.text_input("From")
# message = st.text_area("Message")
# receiver_email = st.text_input("Recipient Email")
# 
# SENDER_EMAIL = "your_email@gmail.com"
# SENDER_PASSWORD = "your_app_password"
# 
# def send_email():
#     msg = MIMEMultipart()
#     msg["From"] = SENDER_EMAIL
#     msg["To"] = receiver_email
#     msg["Subject"] = "You received a postcard 💌"
# 
#     body = f"""Hi {to_name},
# 
# Message:
# {message}
# 
# From,
# {from_name}
# """
#     msg.attach(MIMEText(body, "plain"))
# 
#     with smtplib.SMTP("smtp.gmail.com", 587) as server:
#         server.starttls()
#         server.login(SENDER_EMAIL, SENDER_PASSWORD)
#         server.send_message(msg)
# 
# if st.button("📨 Send Postcard"):
#     if not all([to_name, from_name, message, receiver_email]):
#         st.error("Fill all fields")
#     else:
#         send_email()
#         st.success("Postcard sent 💖")
#

!streamlit run app.py