# -*- coding: utf-8 -*-
"""card-app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nW4K9uhekMcsNEr88q6HkCIpRO702BXr
"""

import streamlit as st
from PIL import Image
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# ---------------- Page config ----------------
st.set_page_config(
    page_title="Send a Postcard 💌",
    layout="centered"
)

st.title("📮 Send a Postcard")

# ---------------- Load image ----------------
try:
    postcard = Image.open("postcard_template.png")
    st.image(postcard, use_container_width=True)
except FileNotFoundError:
    st.warning("Postcard image not found")

# ---------------- Inputs ----------------
to_name = st.text_input("To")
from_name = st.text_input("From")
message = st.text_area("Message")
receiver_email = st.text_input("Recipient Email")

# ---------------- Secrets ----------------
SENDER_EMAIL = st.secrets["SENDER_EMAIL"]
SENDER_PASSWORD = st.secrets["SENDER_PASSWORD"]

# ---------------- Email logic ----------------
def send_email(to_name, from_name, message, receiver_email):
    msg = MIMEMultipart()
    msg["From"] = SENDER_EMAIL
    msg["To"] = receiver_email
    msg["Subject"] = "You received a postcard 💌"

    body = f"""Hi {to_name},

{message}

From,
{from_name}
"""
    msg.attach(MIMEText(body, "plain"))

    with smtplib.SMTP("smtp.gmail.com", 587) as server:
        server.starttls()
        server.login(SENDER_EMAIL, SENDER_PASSWORD)
        server.send_message(msg)

# ---------------- Button ----------------
if st.button("📨 Send Postcard"):
    if not all([to_name, from_name, message, receiver_email]):
        st.error("Please fill in all fields")
    else:
        try:
            send_email(to_name, from_name, message, receiver_email)
            st.success("Postcard sent 💖")
        except Exception as e:
            st.error("Failed to send postcard")
            st.caption(str(e))